name: Static analysis

on:
  - pull_request

jobs:
  static-psalm-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix: # https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
        ocp:
          - 'dev-stable24'
          - 'dev-stable25'
          - 'dev-stable26'
          - 'dev-stable27'
          - 'dev-master'
        php:
          - '8.0'
          - '8.1'
        include:
          - ocp: 'dev-stable27' 
            php: '8.2'
          - ocp: 'dev-stable26' 
            php: '8.2'
          - ocp: 'dev-master' 
            php: '8.2'
    name: Nextcloud ${{ matrix.ocp }} on PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer:v2
          coverage: none
      - name: Remove PHP lockfile
        run: rm composer.lock
      - name: Install dependencies
        run: composer require --dev nextcloud/ocp:${{ matrix.ocp }}
      - name: Run coding standards check
        run: composer run -- psalm --php-version=${{ matrix.php }}
